export const GET_ALL_EMPLOYEE = "GET_ALL_EMPLOYEE";
export const GET_ALL_EMPLOYEE_SUCCEED = "GET_ALL_EMPLOYEE_SUCCEED";
export const GET_ALL_EMPLOYEE_FAIL = "GET_ALL_EMPLOYEE_FAIL";

export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const ADD_EMPLOYEE_SUCCEED = "ADD_EMPLOYEE_SUCCEED";
export const ADD_EMPLOYEE_FAIL = "ADD_EMPLOYEE_FAIL";

